pragma solidity >=0.8.19 <0.9.0;

import { ReyaForkTest } from "../ReyaForkTest.sol";

import { ICoreProxy, ProtocolConfiguration } from "../../../src/interfaces/ICoreProxy.sol";
import { IPassivePerpProxy } from "../../../src/interfaces/IPassivePerpProxy.sol";
import { IPassivePoolProxy } from "../../../src/interfaces/IPassivePoolProxy.sol";
import { IPeripheryProxy } from "../../../src/interfaces/IPeripheryProxy.sol";
import { IOrdersGatewayProxy, Configuration } from "../../../src/interfaces/IOrdersGatewayProxy.sol";

/// The perp's global-config getter exists on the deployed router but not in
/// the autogenerated interface; declared locally with the DEPLOYED 5-field
/// struct (the shared interface's 2-field version is stale — the same
/// mismatch that hid the dustAccountId_DEPRECATED bug).
interface IPerpGlobalConfig {
    struct PerpGlobalConfigData {
        address coreProxy;
        address exchangeProxy_DEPRECATED;
        address oracleManagerAddress;
        uint256 maxAbsFundingRate;
        uint128 dustAccountId_DEPRECATED;
    }

    function getGlobalConfiguration() external view returns (PerpGlobalConfigData memory);
}

/**
 * @title SharedConfigAppliedForkTest (Devnet)
 * @notice A4: effect-level assertions for every devnet package that mirrors
 *         a shared config set — core, passive_perp, passive_pool, periphery,
 *         orders_gateway (oracle_adapters already has
 *         check_adaptersSharedConfig_applied).
 * @dev Cannon SKIPS a failing step with a warning and the build "succeeds",
 *      so a config can be perfectly wired into an include list and still
 *      silently not applied — that is how passive_perp_global_config stayed
 *      broken for weeks. These tests read the on-chain EFFECT of each config
 *      group back, so any silently-skipped step in any package turns into a
 *      red test. Allowlists are asserted as exact sets wherever the expected
 *      membership is known; a dropped AND an extra entry both fail.
 */
contract SharedConfigAppliedForkTest is ReyaForkTest {
    bytes32 constant GLOBAL_FLAG = keccak256(bytes("global"));
    address constant ME_PUBLISHER = 0xD3D5911FE8ab109645f931Cf65B341d5dd672eFB;

    function test_Devnet_CoreSharedConfig_Applied() public view {
        ICoreProxy core = ICoreProxy(sec.core);

        // feature_flags.toml
        require(core.getFeatureFlagAllowAll(GLOBAL_FLAG), "core: global flag not opened");
        require(core.getFeatureFlagAllowAll(keccak256(bytes("createAccount"))), "core: account creation not open");
        require(
            core.getFeatureFlagAllowAll(keccak256(bytes("notifyAccountTransfer"))), "core: account transfer not open"
        );
        // pausers: devnet uses the owner in all four slots; the deniers set
        // must contain it (SetUtil dedups, so exact length is not asserted)
        address[] memory deniers = core.getDeniers(GLOBAL_FLAG);
        bool ownerIsDenier = false;
        for (uint256 i = 0; i < deniers.length; i++) {
            if (deniers[i] == sec.multisig) ownerIsDenier = true;
        }
        require(ownerIsDenier, "core: owner missing from pausers/deniers");

        // protocol_config.toml — every address Core routes through
        ProtocolConfiguration.Data memory cfg = core.getProtocolConfiguration();
        require(cfg.oracleManagerAddress == sec.oracleManager, "core: wrong oracle manager (the B-lite switch)");
        require(cfg.ordersGatewayAddress == sec.ordersGateway, "core: wrong orders gateway");
        require(cfg.passivePoolAddress == sec.pool, "core: wrong passive pool (must be devnet's own)");
        require(cfg.exchangePassNFTAddress == sec.exchangePass, "core: wrong exchange pass");
        require(cfg.feeCollectorAccountId != 0, "core: fee collector account unset");
    }

    function test_Devnet_PassivePerpSharedConfig_Applied() public view {
        IPassivePerpProxy perp = IPassivePerpProxy(sec.perp);

        // global_config.toml — the config whose silent skip cost ~40 steps
        IPerpGlobalConfig.PerpGlobalConfigData memory cfg = IPerpGlobalConfig(sec.perp).getGlobalConfiguration();
        require(cfg.coreProxy == sec.core, "perp: wrong core");
        require(cfg.oracleManagerAddress == sec.oracleManager, "perp: wrong oracle manager");
        require(cfg.maxAbsFundingRate == 0.1e18, "perp: maxAbsFundingRate != 0.1");

        // feature_flags.toml
        require(perp.getFeatureFlagAllowAll(GLOBAL_FLAG), "perp: global flag not opened");
        require(
            perp.isFeatureAllowed(keccak256(bytes("configureFees")), sec.multisig), "perp: owner cannot configure fees"
        );
        require(
            perp.isFeatureAllowed(keccak256(bytes("configureMarket")), sec.multisig),
            "perp: owner cannot configure markets"
        );

        // oraclePushers: EXACTLY the two perp-ob push wallets
        address[] memory pushers = perp.getFeatureFlagAllowlist(keccak256(bytes("oraclePushers")));
        require(pushers.length == 2, "perp: expected exactly two oracle pushers");
        require(
            perp.isFeatureAllowed(keccak256(bytes("oraclePushers")), sec.oraclePusher1)
                && perp.isFeatureAllowed(keccak256(bytes("oraclePushers")), sec.oraclePusher2),
            "perp: a perp-ob pusher is missing"
        );

        // oraclePublishers: EXACTLY the matching-engine EIP-712 signer
        address[] memory publishers = perp.getFeatureFlagAllowlist(keccak256(bytes("oraclePublishers")));
        require(publishers.length == 1, "perp: expected exactly one oracle publisher");
        require(publishers[0] == ME_PUBLISHER, "perp: wrong oracle publisher");
    }

    function test_Devnet_PassivePoolSharedConfig_Applied() public view {
        IPassivePoolProxy pool = IPassivePoolProxy(sec.pool);

        // global_config.toml
        require(pool.getGlobalConfiguration().coreProxy == sec.core, "pool: wrong core");

        // pool_1rusd.toml — created against rUSD, tokenized against devnet's
        // own sRUSD. stakedAsset is the strongest single assertion in this
        // file: pointing it anywhere else (e.g. the Cronos sRUSD) is the
        // shared-supply hazard the whole token split exists to prevent.
        require(pool.getPoolQuoteToken(1) == sec.rusd, "pool: wrong quote token");
        require(pool.stakedAsset(1) == sec.srusd, "pool: tokenized against the wrong sRUSD");

        // feature_flags.toml + open_pool.toml
        require(pool.getFeatureFlagAllowAll(GLOBAL_FLAG), "pool: global flag not opened");
        bytes32 poolEnabled = keccak256(abi.encode(keccak256(bytes("poolEnabled")), uint128(1)));
        bytes32 tokenized = keccak256(abi.encode(keccak256(bytes("tokenizedLiquidity")), uint128(1)));
        bytes32 v2 = keccak256(abi.encode(keccak256(bytes("v2Liquidity")), uint128(1)));
        bytes32 depositFlag = keccak256(abi.encode(keccak256(bytes("deposit")), uint128(1)));
        bytes32 withdrawalFlag = keccak256(abi.encode(keccak256(bytes("withdrawal")), uint128(1)));
        require(pool.getFeatureFlagAllowAll(poolEnabled), "pool: pool 1 not enabled");
        require(pool.getFeatureFlagAllowAll(tokenized), "pool: tokenized liquidity not open");
        require(pool.getFeatureFlagAllowAll(v2), "pool: v2 liquidity not open");
        require(pool.getFeatureFlagAllowAll(depositFlag), "pool: deposits not open");
        require(pool.getFeatureFlagAllowAll(withdrawalFlag), "pool: withdrawals not open");

        // actionMetadataOverwrite: EXACTLY periphery + core
        bytes32 amoFlag = keccak256(bytes("actionMetadataOverwrite"));
        address[] memory amo = pool.getFeatureFlagAllowlist(amoFlag);
        require(amo.length == 2, "pool: expected exactly two actionMetadataOverwrite entries");
        require(
            pool.isFeatureAllowed(amoFlag, sec.periphery) && pool.isFeatureAllowed(amoFlag, sec.core),
            "pool: periphery/core missing from actionMetadataOverwrite"
        );

        // whitelistedCollateral for auto-rebalance: rUSD + devnet's sRUSD
        bytes32 wlFlag = keccak256(abi.encode(keccak256(bytes("whitelistedCollateral")), uint128(1)));
        require(pool.isFeatureAllowed(wlFlag, sec.rusd), "pool: rUSD not whitelisted for rebalance");
        require(pool.isFeatureAllowed(wlFlag, sec.srusd), "pool: sRUSD not whitelisted for rebalance");
    }

    function test_Devnet_PeripherySharedConfig_Applied() public view {
        // global config readback lives in DevnetConfig; this covers the flags
        IPeripheryProxy periphery = IPeripheryProxy(sec.periphery);
        require(periphery.getFeatureFlagAllowAll(GLOBAL_FLAG), "periphery: global flag not opened");
    }

    function test_Devnet_OrdersGatewaySharedConfig_Applied() public view {
        // allowlists live in DevnetConfig; this reads the routing config back
        Configuration.Data memory cfg = IOrdersGatewayProxy(sec.ordersGateway).getConfiguration();
        require(cfg.coreProxy == sec.core, "og: wrong core");
        require(cfg.passivePerpProxy == sec.perp, "og: wrong passive perp");
    }
}
