# Devnet passive perp fees: only tier0, passive pool exchange rebate, zero global discounts
[invoke.passive_perp_set_exchange_passive_pool_rebate]
target = ["PassivePerpProxy"]
fromCall.func = "owner"
func = "setExchangeRebate"
args = [
    "<%= settings.passivePoolExchangeId %>",
    "<%= parseEther(settings.passivePoolExchangeRebateUnscaled) %>",
]
depends = ["invoke.upgrade_passive_perp_proxy"]

[invoke.passive_perp_set_tier0_parameters]
target = ["PassivePerpProxy"]
fromCall.func = "owner"
func = "setFeeTierParameters"
args = [
    "0",
    { takerFee = "<%= parseEther(settings.takerFeeTier0Unscaled) %>", makerFee = "<%= parseEther(settings.makerFeeTier0Unscaled) %>", makerRebate = "0" },
]
depends = ["invoke.upgrade_passive_perp_proxy"]

[invoke.passive_perp_set_global_fee_parameters]
target = ["PassivePerpProxy"]
fromCall.func = "owner"
func = "setGlobalFeeParameters"
args = [
    { ogDiscount = "0", refereeDiscount = "0", referrerRebate = "0", affiliateReferrerRebate = "0", vltzDiscount = "0", spreadDiscount = "0" },
]
depends = ["invoke.upgrade_passive_perp_proxy"]
