[invoke.passive_perp_velocity_config_owner]
target = ["PassivePerpProxy"]
fromCall.func = "owner"
func = "addToFeatureFlagAllowlist"
args = ["<%= keccak256(hexlify('configureDepth')) %>", "<%= settings.owner %>"]
depends = ["invoke.upgrade_passive_perp_proxy"]

[invoke.passive_perp_initialize_velocity_multipliers]
target = ["PassivePerpProxy"]
fromCall.func = "owner"
func = "batchSetMarketConfigurationVelocity"
args = [
    [
        "<%= settings.market1EthId %>",
        "<%= settings.market2BtcId %>",
        "<%= settings.market3SolId %>",
        "<%= settings.market4ArbId %>",
        "<%= settings.market5OpId %>",
        "<%= settings.market6AvaxId %>",
        "<%= settings.market7MkrId %>",
        "<%= settings.market8LinkId %>",
        "<%= settings.market9AaveId %>",
        "<%= settings.market10CrvId %>",
        "<%= settings.market11UniId %>",
        "<%= settings.market12SuiId %>",
        "<%= settings.market13TiaId %>",
        "<%= settings.market14SeiId %>",
        "<%= settings.market15ZroId %>",
        "<%= settings.market16XrpId %>",
        "<%= settings.market17WifId %>",
        "<%= settings.market18Pepe1kId %>",
        "<%= settings.market19PopcatId %>",
        "<%= settings.market20DogeId %>",
        "<%= settings.market21KShibId %>",
        "<%= settings.market22KBonkId %>",
        "<%= settings.market23AptId %>",
        "<%= settings.market24BnbId %>",
        "<%= settings.market25JtoId %>",
        "<%= settings.market26AdaId %>",
        "<%= settings.market27LdoId %>",
        "<%= settings.market28PolId %>",
        "<%= settings.market29NearId %>",
        "<%= settings.market30FtmId %>",
        "<%= settings.market31EnaId %>",
        "<%= settings.market32EigenId %>",
        "<%= settings.market33PendleId %>",
        "<%= settings.market34GoatId %>",
        "<%= settings.market35GrassId %>",
        "<%= settings.market36KNeiroId %>",
        "<%= settings.market37DotId %>",
        "<%= settings.market38LtcId %>",
        "<%= settings.market39PythId %>",
        "<%= settings.market40JupId %>",
        "<%= settings.market41PenguId %>",
        "<%= settings.market42TrumpId %>",
        "<%= settings.market43HypeId %>",
        "<%= settings.market44VirtualId %>",
        "<%= settings.market45Ai16zId %>",
        "<%= settings.market46AixbtId %>",
        "<%= settings.market47SonicId %>",
        "<%= settings.market48FartcoinId %>",
        "<%= settings.market49GriffainId %>",
        "<%= settings.market50WldId %>",
        "<%= settings.market51AtomId %>",
        "<%= settings.market52ApeId %>",
        "<%= settings.market53TonId %>",
        "<%= settings.market54OndoId %>",
        "<%= settings.market55TrxId %>",
        "<%= settings.market56InjId %>",
        "<%= settings.market57MoveId %>",
        "<%= settings.market58BeraId %>",
        "<%= settings.market59LayerId %>",
        "<%= settings.market60TaoId %>",
        "<%= settings.market61IpId %>",
        "<%= settings.market62MeId %>",
        "<%= settings.market63PumpId %>",
        "<%= settings.market64MorphoId %>",
        "<%= settings.market65SyrupId %>",
        "<%= settings.market66AeroId %>",
        "<%= settings.market67KaitoId %>",
        "<%= settings.market68ZoraId %>",
        "<%= settings.market69ProveId %>",
        "<%= settings.market70PaxgId %>",
        "<%= settings.market71YzyId %>",
        "<%= settings.market72XplId %>",
        "<%= settings.market73WlfiId %>",
        "<%= settings.market74LineaId %>",
        "<%= settings.market75MegaId %>",
    ],
    [
        "<%= parseEther(settings.market1Eth_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market2Btc_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market3Sol_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market4Arb_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market5Op_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market6Avax_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market7Mkr_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market8Link_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market9Aave_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market10Crv_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market11Uni_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market12Sui_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market13Tia_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market14Sei_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market15Zro_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market16Xrp_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market17Wif_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market18Pepe1k_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market19Popcat_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market20Doge_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market21KShib_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market22KBonk_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market23Apt_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market24Bnb_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market25Jto_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market26Ada_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market27Ldo_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market28Pol_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market29Near_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market30Ftm_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market31Ena_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market32Eigen_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market33Pendle_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market34Goat_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market35Grass_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market36KNeiro_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market37Dot_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market38Ltc_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market39Pyth_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market40Jup_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market41Pengu_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market42Trump_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market43Hype_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market44Virtual_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market45Ai16z_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market46Aixbt_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market47Sonic_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market48Fartcoin_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market49Griffain_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market50Wld_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market51Atom_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market52Ape_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market53Ton_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market54Ondo_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market55Trx_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market56Inj_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market57Move_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market58Bera_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market59Layer_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market60Tao_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market61Ip_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market62Me_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market63Pump_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market64Morpho_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market65Syrup_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market66Aero_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market67Kaito_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market68Zora_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market69Prove_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market70Paxg_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market71Yzy_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market72Xpl_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market73Wlfi_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market74Linea_velocityMultiplierUnscaled) %>",
        "<%= parseEther(settings.market75Mega_velocityMultiplierUnscaled) %>",
    ],
]
depends = [
    "invoke.passive_perp_velocity_config_owner",
    "invoke.create_market_75mega",
]
