// SPDX-License-Identifier: UNLICENSED
// !! THIS FILE WAS AUTOGENERATED BY abi-to-sol v0.8.0. SEE SOURCE BELOW. !!
pragma solidity ^0.8.4;

interface IOracleAdaptersProxy {
    /**
     * @notice Sets the new share price for a given asset pair id
     * Note that the price of the asset pair will start from 1.
     * @param input The input data.
     */
    function updateLmTokenPrice(UpdateLmTokenPriceInput memory input) external;

    /**
     * @notice Sets the new share price configuration for a given asset pair id
     * @param assetPairId The asset pair id
     * @param config The configuration data
     */
    function setLmTokenPriceConfiguration(
        string memory assetPairId,
        LmTokenPriceConfigurationData memory config
    ) external;

    /**
     * @notice Returns the share price configuration for a given asset pair id
     * @param assetPairId The asset pair id
     * @return The configuration data
     */
    function getLmTokenPriceConfiguration(
        string memory assetPairId
    ) external view returns (LmTokenPriceConfigurationData memory);

    function setConfiguration(Configuration memory config) external;

    function getConfiguration() external pure returns (Configuration memory);

    function oracleId() external view returns (bytes32 oracleId);

    function fulfillOracleQuery(bytes calldata signedOffchainData) external payable;

    function getLatestPricePayload(
        string memory assetPairId
    ) external view returns (StorkPricePayload memory);

    function addToFeatureFlagAllowlist(bytes32 feature, address account) external;

    function removeFromFeatureFlagAllowlist(bytes32 feature, address account) external;

    error StorkPayloadSignatureInvalid(StorkSignedPayload storkSignedPayload);

    error StorkPayloadOlderThanLatest(
        StorkPricePayload currentPricePayload,
        StorkPricePayload latestPricePayload
    );

    error UnauthorizedPublisher(address unathorizedPublisher);

    error FeatureUnavailable(bytes32 which);

    function getFeatureFlagAllowAll(bytes32 feature) external view returns (bool);

    function getFeatureFlagAllowlist(bytes32 feature) external view returns (address[] memory);

    function getFeatureFlagDenyAll(bytes32 feature) external view returns (bool);
}

struct StorkSignedPayload {
    address oraclePubKey;
    StorkPricePayload pricePayload;
    bytes32 r;
    bytes32 s;
    uint8 v;
}

struct StorkPricePayload {
    string assetPairId;
    uint256 timestamp;
    uint256 price;
}

struct Configuration {
    address storkVerifyContract;
}

struct UpdateLmTokenPriceInput {
    string assetPairId;
    uint256 price;
    uint256 vestingPeriodInSeconds;
}

struct LmTokenPriceConfigurationData {
    uint256 priceLowerBound;
    uint256 priceUpperBound;
}
