# Devnet passive perp fees: single tier (tier0), passive pool exchange rebate
[invoke.passive_perp_set_exchange_passive_pool_rebate]
target = ["PassivePerpProxy"]
fromCall.func = "owner"
func = "setExchangeRebate"
args = [
    "<%= settings.passivePoolExchangeId %>",
    "<%= parseEther(settings.passivePoolExchangeRebateUnscaled) %>",
]
depends = ["invoke.upgrade_passive_perp_proxy"]

[invoke.passive_perp_set_tier0_parameters]
target = ["PassivePerpProxy"]
fromCall.func = "owner"
func = "setFeeTierParameters"
args = [
    "0",
    { takerFee = "<%= parseEther(settings.takerFeeTier0Unscaled) %>", makerFee = "<%= parseEther(settings.makerFeeTier0Unscaled) %>", makerRebate = "<%= parseEther(settings.makerRebateTier0Unscaled) %>" },
]
depends = ["invoke.upgrade_passive_perp_proxy"]

[invoke.passive_perp_set_global_fee_parameters]
target = ["PassivePerpProxy"]
fromCall.func = "owner"
func = "setGlobalFeeParameters"
args = [
    { ogDiscount = "<%= parseEther(settings.ogDiscountUnscaled) %>", refereeDiscount = "<%= parseEther(settings.refereeDiscountUnscaled) %>", referrerRebate = "<%= parseEther(settings.referrerRebateUnscaled) %>", affiliateReferrerRebate = "<%= parseEther(settings.affiliateReferrerRebateUnscaled) %>", vltzDiscount = "<%= parseEther(settings.vltzDiscountUnscaled) %>", spreadDiscount = "<%= parseEther(settings.spreadDiscountUnscaled) %>" },
]
depends = ["invoke.upgrade_passive_perp_proxy"]
