include = [
    "utils/deploy_proxy_devnet.toml",
    "utils/upgrade_proxy.toml",
    "configs/feature_flags.toml",
    "configs/global_config_devnet.toml",
    "configs/tokens-devnet/usdc.toml",
    "configs/tokens-devnet/weth.toml",
]
