include = [
    "utils/deploy_proxy_devnet.toml",
    "utils/upgrade_proxy.toml",
    "configs/feature_flags_devnet.toml",
    "configs/protocol_config_devnet.toml",
    "configs/instruments.toml",
    "configs/exchanges_devnet.toml",
    "configs/tokens/rusd_devnet.toml",
    "configs/tokens/weth_devnet.toml",
]
